package review;


import myBookings.*;
import manger_services.BookingService;
import manger_services.LeisureCentreManager;
import database.DatabaseConnector;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;


public class ReviewPage extends javax.swing.JFrame {
    
    private final DatabaseConnector db = new DatabaseConnector();
    
    LeisureCentreManager leisureCentreManager;
    BookingService bookingService;
    
    private final int booking_id;
    
     
    /**
     * Creates new form PurchasePage
     * @param booking_id
     */
    public ReviewPage(int booking_id) {
        initComponents();
        this.booking_id = booking_id;
        
        leisureCentreManager = new LeisureCentreManager();
        bookingService = new BookingService();
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnEditLesson = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboRating = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaText = new javax.swing.JTextArea();

        jTable1.setBackground(new java.awt.Color(255, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Duration", "Date"
            }
        ));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Review Lesson");
        setBackground(new java.awt.Color(204, 255, 255));
        setLocation(new java.awt.Point(120, 140));
        setType(java.awt.Window.Type.POPUP);

        jBtnEditLesson.setBackground(new java.awt.Color(255, 102, 51));
        jBtnEditLesson.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnEditLesson.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEditLesson.setText("Rate Lesson");
        jBtnEditLesson.setActionCommand("btnBook");
        jBtnEditLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewLesson(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 204, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 128, 59));
        jLabel7.setText("Text:");

        jComboRating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Please Select Rating----", "1", "2", "3", "4", "5" }));
        jComboRating.setToolTipText("");
        jComboRating.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 0)));
        jComboRating.setVerifyInputWhenFocusTarget(false);

        jLabel9.setBackground(new java.awt.Color(0, 204, 204));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 128, 59));
        jLabel9.setText("Rating");

        jTextAreaText.setColumns(20);
        jTextAreaText.setRows(5);
        jScrollPane2.setViewportView(jTextAreaText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboRating, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEditLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboRating, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBtnEditLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   
    
 
        // Edits an existing booking with a newly selected appointment slot
    private void reviewLesson(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewLesson
        
        String reviewText = jTextAreaText.getText().trim();
        String ratingStr = (String) jComboRating.getSelectedItem();

        if (ratingStr == null) {
            JOptionPane.showMessageDialog(null, "Please select a rating.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (reviewText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a review.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int rating;
        try {
            rating = Integer.parseInt(ratingStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid rating selected.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (bookingService.checkAlreadyReviewed(booking_id)) {
            JOptionPane.showMessageDialog(null, "You already reviewed this lesson.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!bookingService.isLessonAttended(booking_id)) {
            JOptionPane.showMessageDialog(null, "You can only review an attended lesson.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        bookingService.addReview(booking_id, reviewText, rating);
        JOptionPane.showMessageDialog(null, "Lesson reviewed successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_reviewLesson



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEditLesson;
    private javax.swing.JComboBox<String> jComboRating;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaText;
    // End of variables declaration//GEN-END:variables
    
}
