package report;




import manger_services.BookingService;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class ViewReport extends javax.swing.JFrame {
    

    BookingService bookingService;
  

     
    /**
     * Creates new form PurchasePage
     */
    public ViewReport() {
        initComponents();
   
         bookingService = new BookingService();

        loadLessonSummaryReportIntoTable();
        loadHighestIncomeExerciseReportIntoTable();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLessonSummaryReport = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableHighestIncomeSubjectReport = new javax.swing.JTable();

        jTable1.setBackground(new java.awt.Color(255, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Duration", "Date"
            }
        ));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Report");
        setBackground(new java.awt.Color(204, 255, 255));
        setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        setLocation(new java.awt.Point(140, 160));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jTableLessonSummaryReport.setBackground(new java.awt.Color(255, 153, 153));
        jTableLessonSummaryReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Excercise", "Date", "Day", "Time", "No. Members", "Average Rating"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLessonSummaryReport.setShowGrid(true);
        jScrollPane2.setViewportView(jTableLessonSummaryReport);

        jTabbedPane1.addTab("Lesson summary report", jScrollPane2);

        jTableHighestIncomeSubjectReport.setBackground(new java.awt.Color(255, 153, 153));
        jTableHighestIncomeSubjectReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableHighestIncomeSubjectReport.setShowGrid(true);
        jScrollPane3.setViewportView(jTableHighestIncomeSubjectReport);

        jTabbedPane1.addTab("Highest Earning Excercise", jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    
   private void loadLessonSummaryReportIntoTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) jTableLessonSummaryReport.getModel();
            model.setRowCount(0);

            model = bookingService.generateLessonReport(model);
            jTableLessonSummaryReport.setModel(model);

        } catch (Exception e) {
            System.out.println("loadLessonSummaryReportIntoTable: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Unable to load lesson summary report. Please try again.");
        }
    }

    private void loadHighestIncomeExerciseReportIntoTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) jTableHighestIncomeSubjectReport.getModel();
            model.setRowCount(0);

            model = bookingService.generateIncomeReport(model);
            jTableHighestIncomeSubjectReport.setModel(model);

        } catch (Exception e) {
            System.out.println("loadHighestIncomeExerciseReportIntoTable: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Unable to load income report. Please try again.");
        }
    }
    

    
  
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableHighestIncomeSubjectReport;
    private javax.swing.JTable jTableLessonSummaryReport;
    // End of variables declaration//GEN-END:variables
    
}
