package myBookings;


import manger_services.BookingService;
import manger_services.LeisureCentreManager;
import database.DatabaseConnector;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;


public class EditBookingsPage extends javax.swing.JFrame {
    
    private final DatabaseConnector db = new DatabaseConnector();
    
    LeisureCentreManager leisureCentreManager;
    BookingService bookingService;
    
    private final int booking_id;
    
    int memberId = 9;

     
    /**
     * Creates new form PurchasePage
     * @param booking_id
     */
    public EditBookingsPage(int booking_id) {
        initComponents();
        this.booking_id = booking_id;
        
        leisureCentreManager = new LeisureCentreManager();
        bookingService = new BookingService();
  
        loadBookingForEdit(booking_id);
        
     
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnEditLesson = new javax.swing.JButton();
        jComboTime = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboDate = new javax.swing.JComboBox<>();
        jComboDay = new javax.swing.JComboBox<>();
        jComboExercise = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        jTable1.setBackground(new java.awt.Color(255, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Duration", "Date"
            }
        ));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Booking");
        setBackground(new java.awt.Color(204, 255, 255));
        setLocation(new java.awt.Point(120, 140));
        setType(java.awt.Window.Type.POPUP);

        jBtnEditLesson.setBackground(new java.awt.Color(0, 204, 202));
        jBtnEditLesson.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnEditLesson.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEditLesson.setText("Edit Booking");
        jBtnEditLesson.setActionCommand("btnBook");
        jBtnEditLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBooking(evt);
            }
        });

        jComboTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Please Select Time----" }));
        jComboTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 0)));
        jComboTime.setVerifyInputWhenFocusTarget(false);

        jLabel4.setBackground(new java.awt.Color(0, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 128, 59));
        jLabel4.setText("Time");

        jLabel7.setBackground(new java.awt.Color(0, 204, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 128, 59));
        jLabel7.setText("Date:");

        jLabel8.setBackground(new java.awt.Color(0, 204, 204));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 128, 59));
        jLabel8.setText("Day:");

        jComboDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Please Select Date----" }));
        jComboDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 0)));
        jComboDate.setVerifyInputWhenFocusTarget(false);
        jComboDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                populateAvailableDays(evt);
            }
        });

        jComboDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Please Select Day----" }));
        jComboDay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 0)));
        jComboDay.setVerifyInputWhenFocusTarget(false);
        jComboDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                populateAvailableTimes(evt);
            }
        });

        jComboExercise.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Please Select Exercise----", "Yoga", "Zumba", "Aquacise", "Box Fit", "Body Blitz" }));
        jComboExercise.setToolTipText("");
        jComboExercise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 0)));
        jComboExercise.setVerifyInputWhenFocusTarget(false);
        jComboExercise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                populateAvailableDates(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 204, 204));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 128, 59));
        jLabel9.setText("Exercise Name: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboDate, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboExercise, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboDay, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboTime, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEditLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboExercise, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboDate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboDay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboTime, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jBtnEditLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   
    // Loads selected booking data into combo boxes for editing
    private void loadBookingForEdit(int bookingId) {
        String query = "SELECT b.booking_id, e.exercise_name, l.lesson_date, l.day_name, l.time_slot, b.status " +
                       "FROM bookings b " +
                       "JOIN lessons l ON b.lesson_id = l.lesson_id " +
                       "JOIN exercise_types e ON l.exercise_id = e.exercise_id " +
                       "WHERE b.booking_id = ?";

        try (Connection con = db.connect();
             PreparedStatement ps = con.prepareStatement(query)) {

            ps.setInt(1, bookingId);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String exerciseName = rs.getString("exercise_name");
                String lessonDate = rs.getString("lesson_date");
                String dayName = rs.getString("day_name");
                String timeSlot = rs.getString("time_slot");

                jComboExercise.setSelectedItem(exerciseName);
                jComboDate.setSelectedItem(lessonDate);
                jComboDay.setSelectedItem(dayName);
                jComboTime.setSelectedItem(timeSlot);
            }

        } catch (SQLException e) {
            System.out.println("loadBookingForEdit: Failed to load record - " + e.getMessage());
        }
    }

    
 
        // Edits an existing booking with a newly selected appointment slot
    private void updateBooking(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBooking
        
        String exerciseName = (String) jComboExercise.getSelectedItem();
        String date = (String) jComboDate.getSelectedItem();
        String dayName = (String) jComboDay.getSelectedItem();
        String timeSlot = (String) jComboTime.getSelectedItem();
        
        //int bookingId = 5;

        int lessonId = bookingService.fetchAvailableLessonId(exerciseName, date, dayName, timeSlot);

        if (lessonId == 0) {
            JOptionPane.showMessageDialog(null, "No matching lesson found.");
        } else if (bookingService.isLessonFull(lessonId)) {
            JOptionPane.showMessageDialog(null, "The selected lesson is full.");
        } else if (bookingService.hasTimeConflict(memberId, lessonId)) {
            JOptionPane.showMessageDialog(null, "Cannot change booking: you already have another lesson at this time.");
        } else {
            bookingService.changeBooking(booking_id, lessonId, memberId);
            JOptionPane.showMessageDialog(null, "Booking changed successfully.");
        }

    }//GEN-LAST:event_updateBooking
    // Populates dates based on selected expertise and physiotherapist
    private void populateAvailableDates(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_populateAvailableDates
        
        jComboDate.removeAllItems();

        String exerciseName = (String) jComboExercise.getSelectedItem();
        System.out.println("Selected exercise: [" + exerciseName + "]");

        if (exerciseName == null || exerciseName.trim().isEmpty() || exerciseName.equals("Select Exercise")) {
            return;
        }

        List<String> dates = leisureCentreManager.getAvailableLessonDates(exerciseName.trim(), memberId);

        if (dates.isEmpty()) {
            jComboDate.addItem("No available dates");
        } else {
            for (String date : dates) {
                jComboDate.addItem(date);
            }
        }
    }//GEN-LAST:event_populateAvailableDates
    // Populates available days based on expertise, physio, and selected date
    private void populateAvailableDays(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_populateAvailableDays
        jComboDay.removeAllItems();
        String exerciseName = (String) jComboExercise.getSelectedItem();
        String selectedDate = (String) jComboDate.getSelectedItem();

        List<String> days = leisureCentreManager.getAvailableDays(exerciseName, selectedDate, memberId);
        for (String day : days) {
            jComboDay.addItem(day);
        }
    }//GEN-LAST:event_populateAvailableDays
    // Populates available time slots for a given date and day
    private void populateAvailableTimes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_populateAvailableTimes
        jComboTime.removeAllItems();

        String exerciseName = (String) jComboExercise.getSelectedItem();
        String selectedDate = (String) jComboDate.getSelectedItem();
        String selectedDay = (String) jComboDay.getSelectedItem();

        List<String> times = leisureCentreManager.getAvailableTimeSlots(
                exerciseName, selectedDate, selectedDay, memberId
        );

        for (String time : times) {
            jComboTime.addItem(time);
        }
    }//GEN-LAST:event_populateAvailableTimes



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEditLesson;
    private javax.swing.JComboBox<String> jComboDate;
    private javax.swing.JComboBox<String> jComboDay;
    private javax.swing.JComboBox<String> jComboExercise;
    private javax.swing.JComboBox<String> jComboTime;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
